CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255)                            NOT NULL UNIQUE,
    name  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL UNIQUE,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         text                                    NOT NULL,
    category_id        BIGINT,
    confirmed_requests BIGINT,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    description        text                                    NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    user_id            BIGINT,
    lat                double precision,
    lon                double precision,
    paid               boolean,
    participant_limit  BIGINT,
    published_on       VARCHAR(255),
    request_moderation boolean,
    state              VARCHAR(255)                            NOT NULL,
    title              text                                    NOT NULL,
    views              BIGINT,
    CONSTRAINT pk_event PRIMARY KEY (id),
    foreign key (category_id) references categories (id),
    foreign key (user_id) references users (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created  VARCHAR(255)                            NOT NULL,
    event_id BIGINT,
    user_id  BIGINT,
    status   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    foreign key (event_id) references events (id),
    foreign key (user_id) references users (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned boolean,
    title  VARCHAR(255) unique,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_to_event
(
    compilation_id BIGINT,
    event_id       BIGINT,
    foreign key (compilation_id) references compilations (id),
    foreign key (event_id) references events (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      VARCHAR(255)                            NOT NULL,
    event_id  BIGINT                                  NOT NULL,
    author_id BIGINT                                  NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id),
    foreign key (event_id) references events (id),
    foreign key (author_id) references users (id)
);

