CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL UNIQUE,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255)                            NOT NULL UNIQUE,
    name  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_id       BIGINT,
    confirmedRequests BIGINT,
    createdOn         VARCHAR(255)                            NOT NULL,
    description       VARCHAR(255)                            NOT NULL,
    eventDate         VARCHAR(255)                            NOT NULL,
    user_id           BIGINT,
    lat               double precision,
    lon               double precision,
    paid              boolean,
    participantLimit  BIGINT,
    publishedOn       VARCHAR(255)                            NOT NULL,
    requestModeration boolean,
    state             VARCHAR(255)                            NOT NULL,
    title             VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id)
);
